site_name: NDP Documentation
site_url: https://nationaldataplatform.org/documentation

nav:
  - Home: index.md
  - About: 
    - About NDP: general/about.md
    - Key Features: general/key-features.md
  - Start: 
    - Sign In: start/signin.md
  - Catalog:
    - Exploring Data Catalog: catalog/exploring-data-catalog.md
    - Register your data: catalog/register-data.md
    - Bringing your data using CKAN harvest: catalog/bringing-your-data.md
    - Register your Open Knowledge Network: catalog/register-okn.md
  - Jupyter:
    - NDP Jupyterhub: jupyter/jupyterhub.md
    - NDP Widget: jupyter/widget.md
    - GitHub Extension: jupyter/github-extension.md
  - Workspace: 
    - NDP Workspace: workspace/index.md
    - Tutorial: workspace/set-up.md
  - NDP PoP:
    - NDP PoP: pop/index.md
  - NDP Education Hub:
    - NDP Modules:
        - NDP Modules: ndp-modules/index.md 
        - Understanding NDP Modules: ndp-modules/understanding-modules.md
        - Modules Components: ndp-modules/module-components.md
        - Module Creation Tutorial: ndp-modules/module-tutorial.md
    - NDP Classroom:
        - NDP Classroom: ndp-classroom/index.md
        - Set Up: ndp-classroom/set-up.md
    - Courselets:
        - NDP Courselets: courselets/ndp-courselets.md
        - Sample Courselet: courselets/sample-courselet.md
  - Services: 
    - MLFlow: services/mlflow.md
    - LLM: services/llm.md
  - Demos:
    - NASA HLS Demo: demos/nasa-hls-demo.md
  - Contact: general/contact.md

theme:
  name: material
  logo: images/logos/ndp-logo.png
  features:
    - content.code.copy
    - navigation.top
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to light mode
repo_url: https://github.com/national-data-platform

extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/nationaldataplatform/
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/natldataplat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/national-data-platform/

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

