site_name: Wildfire Commons Documentation
site_url: https://documentation.wildfirecommons.org/documentation

nav:
  - Home: index.md
  - About: 
    - About Wildfire Commons: general/about.md
    - Key Features: general/key-features.md
  - Start: 
    - Getting Started: start/getting-started.md
    - Sign In: start/signin.md
    - Working Tutorial: start/working-tutorial.md
  - Explore The Catalog:
    - Data Catalog: catalog/catalog.md
    #- Advanced Search: catalog/advanced-search.md
  - Add Resources to the Commons:
    - Register your Data, Models and Services: add-resources/register-data.md
    - Curated Catalogs: 
      - Learn about Curated Catalogs: add-resources/curated-catalog/about.md
      - Add your Curated Catalog: add-resources/curated-catalog/add-data-catalog.md
    #- Register a Model:  add-resources/register-model.md
    #- Register a Service: add-resources/register-service.md
  - FireForge:
    - Jupyterhub: fireforge/jupyterhub.md
    #- Widget: jupyter/widget.md
    - Bring your own image: fireforge/bring-your-own-image.md
    #- Frequently Encountered Issues: jupyter/fei.md
    #- Workspace: 
    #  - Workspace: workspace/index.md
    #  - Tutorial: workspace/set-up.md
  - Data Challenges: 
      - Host a Data Challenge: data-challenges/hosting-a-data-challenge.md
      - Join a Data Challenge: data-challenges/participating-in-data-challenge.md
  - Pathfinders:
    -  Add a Pathfinder Project: pathfinders/add-pathfinder-project.md
  - Policies and Guidelines: 
    - Terms of Use: policies/terms-of-use.md
    - Privacy Policy: policies/privacy-policy.md
    - Code of Conduct: policies/code-of-conduct.md
  - Contact: general/contact.md

theme:
  name: material
  logo: images/logos/wstc-logo.png
  features:
    - content.code.copy
    - navigation.top
  palette:
    - scheme: default
      primary: brown
      accent: orange
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: orange
      toggle:
        icon: material/eye
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/wildfirecommons.bsky.social
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/14463867/

extra_css:
  - styles/custom-theme.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
