site_name: Wildfire Commons Documentation
site_url: https://wildfirecommons.org/documentation

nav:
  - Home: index.md
  - About: 
    - About Wildfire Commons: general/about.md
    - Key Features: general/key-features.md
    - Institutions: general/institutions.md
  - Start: 
    - Sign In: start/signin.md
    - Expert Network: start/expertnetwork.md
    - Pathfinders: start/pathfinders.md
  - Catalog:
    - Exploring Data Catalog: catalog/catalog.md
    - Advanced Search: catalog/advanced-search.md
    - Register your data: catalog/register-data.md
  - FireForge:
    - Jupyterhub: jupyter/jupyterhub.md
    - Widget: jupyter/widget.md
    - Bring your own image: jupyter/bring-your-own-image.md
    - Frequently Encountered Issues: jupyter/fei.md
    - Workspace: 
      - Workspace: workspace/index.md
      - Tutorial: workspace/set-up.md
  - Policies and Guidelines: 
        - Terms of Use: policies/terms-of-use.md
        - Privacy Policy: policies/privacy-policy.md
        - Code of Conduct: policies/code-of-conduct.md
        - PVC Policy: policies/pvc-policy.md
  - Contact: general/contact.md

theme:
  name: material
  logo: docs/general/images/logos/wildfirecommons.png
  features:
    - content.code.copy
    - navigation.top
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/eye
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/wildfirecommons.bsky.social
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/14463867/

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg